### ISSUE TITLE
Job generator does not respect build types

### ISSUE THREAD

**Issue by j-stephan** [alpaka-group/alpaka-job-matrix-library#24]
Example:

https://gitlab.com/hzdr/crp/alpaka/-/jobs/4772261973

The generated job is called `[...]_Release` but the [CMake command line](https://gitlab.com/hzdr/crp/alpaka/-/jobs/4772261973#L1666) contains `-DCMAKE_BUILD_TYPE=Debug`.

**Comment by j-stephan** [comment]
Ah, nevermind. I just saw that we have a special rule for gcc-9 in our build scripts outside of the job generator.

**Comment by SimeonEhrig** [comment]
By the way. Yaml generation is user specific and not done by the alpaka-job-matrix library.
